### ISSUE TITLE
New callback scheme is not python 3.5 compatible

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#138]
Running the editor or examples ends in an exception:
```
remi.server      INFO     Started websocket server 0.0.0.0:50196
remi.server      INFO     Started httpserver http://127.0.0.1:8082/
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 50197)
Traceback (most recent call last):
----------------------------------------
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\socketserver.py", line 625, in process_request_thread
----------------------------------------
    self.finish_request(request, client_address)
Exception happened during processing of request from ('127.0.0.1', 50198)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\socketserver.py", line 354, in finish_request
----------------------------------------
    self.RequestHandlerClass(request, client_address, self)
  File "C:/Users/ayori/PycharmProjects/remi/editor/editor.py", line 284, in __init__
    super(Editor, self).__init__(*args, static_file_path=editor_res_path)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\site-packages\remi-0.1-py3.5.egg\remi\server.py", line 350, in __init__
    super(App, self).__init__(request, client_address, server)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\socketserver.py", line 681, in __init__
    self.handle()
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\http\server.py", line 422, in handle
    self.handle_one_request()
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\http\server.py", line 410, in handle_one_request
    method()
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\site-packages\remi-0.1-py3.5.egg\remi\server.py", line 763, in do_GET
    self._process_all(path)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\site-packages\remi-0.1-py3.5.egg\remi\server.py", line 788, in _process_all
    self.client.root = self.main(*self.server.userdata)
  File "C:/Users/ayori/PycharmProjects/remi/editor/editor.py", line 326, in main
    self.toolbar.add_command('/res/delete.png', self.toolbar_delete_clicked, 'Delete Widget')
  File "C:\Users\ayori\PycharmProjects\remi\editor\editor_widgets.py", line 92, in add_command
    icon.set_on_click_listener(callback)
TypeError: set_on_click_listener() missing 1 required positional argument: 'funcname'
Traceback (most recent call last):
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\socketserver.py", line 625, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:/Users/ayori/PycharmProjects/remi/editor/editor.py", line 284, in __init__
    super(Editor, self).__init__(*args, static_file_path=editor_res_path)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\site-packages\remi-0.1-py3.5.egg\remi\server.py", line 350, in __init__
    super(App, self).__init__(request, client_address, server)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\socketserver.py", line 681, in __init__
    self.handle()
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\http\server.py", line 422, in handle
    self.handle_one_request()
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\http\server.py", line 410, in handle_one_request
    method()
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\site-packages\remi-0.1-py3.5.egg\remi\server.py", line 763, in do_GET
    self._process_all(path)
  File "C:\Users\ayori\AppData\Local\Programs\Python\Python35\lib\site-packages\remi-0.1-py3.5.egg\remi\server.py", line 788, in _process_all
    self.client.root = self.main(*self.server.userdata)
  File "C:/Users/ayori/PycharmProjects/remi/editor/editor.py", line 326, in main
    self.toolbar.add_command('/res/delete.png', self.toolbar_delete_clicked, 'Delete Widget')
  File "C:\Users\ayori\PycharmProjects\remi\editor\editor_widgets.py", line 92, in add_command
    icon.set_on_click_listener(callback)
TypeError: set_on_click_listener() missing 1 required positional argument: 'funcname'

```

**Comment by dddomodossola** [comment]
Unable to reproduce the bug. From the traceback you provided it seems that (maybe) you have forgotten to install the new remi version in that specific python installation. Is it possible?

**Comment by MrYsLab** [comment]
It seems as though the install somehow was corrupted. I installed again and all seems fine.
