### ISSUE TITLE
Dragging widgets in "callback" editor ends in exception

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#139]
Windows 10 running python.  Here is the console output:

```
remi.server      INFO     Started websocket server 0.0.0.0:50328
remi.server      INFO     Started httpserver http://127.0.0.1:8082/
new project
remi.server.ws   INFO     connection established: ('127.0.0.1', 50330)
remi.server.ws   INFO     handshake complete
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "C:\Users\ayori\PycharmProjects\remi\remi\server.py", line 254, in on_message
    callback(**param_dict)
  File "C:\Users\ayori\PycharmProjects\remi\editor\editor_widgets.py", line 372, in on_dropped
    self.prompt_new_widget()
TypeError: prompt_new_widget() takes exactly 2 arguments (1 given)

``

**Comment by dddomodossola** [comment]
Now fixed. Thank you.
