### ISSUE TITLE
Associated a signal with slider and reopening file in editor, causes exception

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#140]
I created a simple project that contains a top level widget with a single slider. I associate the slider with an onclick app signal connection. 

I am running the editor using python 3.5 on Ubuntu 16.10 and using the chrome browser.

Here is the generated code:
```

import remi.gui as gui
from remi.gui import *
from remi import start, App


class untitled(App):
    def __init__(self, *args):
        super(untitled, self).__init__(*args, static_file_path='./res/')
    
    def idle(self):
        #idle function called every update cycle
        pass
    
    def main(self):
        return untitled.construct_ui(self)
        
    @staticmethod
    def construct_ui(self):
        top = Widget()
        top.attributes['editor_varname'] = "top"
        top.attributes['editor_newclass'] = "False"
        top.attributes['class'] = "Widget"
        top.attributes['editor_constructor'] = "()"
        top.attributes['editor_baseclass'] = "Widget"
        top.attributes['editor_tag_type'] = "widget"
        top.style['top'] = "232.34375px"
        top.style['position'] = "absolute"
        top.style['display'] = "block"
        top.style['height'] = "250px"
        top.style['left'] = "361px"
        top.style['width'] = "250px"
        top.style['margin'] = "0px auto"
        top.style['overflow'] = "auto"
        slider = Slider('60',60,255,1)
        slider.attributes['min'] = "60"
        slider.attributes['editor_varname'] = "slider"
        slider.attributes['editor_newclass'] = "False"
        slider.attributes['autocomplete'] = "off"
        slider.attributes['class'] = "range"
        slider.attributes['editor_constructor'] = "('60',60,255,1)"
        slider.attributes['editor_baseclass'] = "Slider"
        slider.attributes['type'] = "range"
        slider.attributes['max'] = "255"
        slider.attributes['editor_tag_type'] = "widget"
        slider.attributes['value'] = "60"
        slider.attributes['step'] = "1"
        slider.style['top'] = "102px"
        slider.style['position'] = "absolute"
        slider.style['display'] = "block"
        slider.style['height'] = "30px"
        slider.style['left'] = "98px"
        slider.style['width'] = "100px"
        slider.style['margin'] = "0px auto"
        slider.style['overflow'] = "auto"
        top.append(slider,'slider')
        top.set_on_click_listener(self.onclick_top)
        

        self.top = top
        return self.top
    
    def onclick_top(self,emitter):
        pass



#Configuration
configuration = {'config_project_name': 'untitled', 'config_address': '0.0.0.0', 'config_start_browser': True, 'config_port': 8081, 'config_resourcepath': './res/', 'config_enable_file_cache': True, 'config_multiple_instance': True}

if __name__ == "__main__":
    # start(MyApp,address='127.0.0.1', port=8081, multiple_instance=False,enable_file_cache=True, update_interval=0.1, start_browser=True)
    start(untitled, address=configuration['config_address'], port=configuration['config_port'], 
                        multiple_instance=configuration['config_multiple_instance'], 
                        enable_file_cache=configuration['config_enable_file_cache'],
                        start_browser=configuration['config_start_browser'])
```

After saving the file and trying to reload it in the editor, an exception is thrown:

```
remi.server.ws   INFO     connection established: ('127.0.0.1', 36308)
remi.server.ws   INFO     handshake complete
remi.server.ws   INFO     connection established: ('127.0.0.1', 36338)
remi.server.ws   INFO     handshake complete
remi.server.ws   INFO     connection established: ('127.0.0.1', 36386)
remi.server.ws   INFO     handshake complete
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/remi/server.py", line 254, in on_message
    callback(**param_dict)
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 1289, in confirm_dialog
    return self.eventManager.propagate(self.EVENT_ONCONFIRM, ())
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 2265, in confirm_value
    return self.eventManager.propagate(self.EVENT_ONCONFIRMVALUE, params)
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
  File "editor.py", line 528, in on_open_dialog_confirm
    widgetTree = self.project.load(filelist[0], self.projectConfiguration)
  File "editor.py", line 115, in load
    return value.construct_ui(self)
  File "/home/afy/remi2/remi-master/editor/click.py", line 57, in construct_ui
    top.set_on_click_listener(self.onclick_top)
AttributeError: 'Project' object has no attribute 'onclick_top'
remi.server.ws   INFO     connection established: ('127.0.0.1', 36596)
remi.server.ws   INFO     handshake complete
remi.server.ws   INFO     connection established: ('127.0.0.1', 36620)
remi.server.ws   INFO     handshake complete


```

**Comment by MrYsLab** [comment]
I just created a similar project with a button instead of a slider and this also throws an exception on trying to open the saved file in the editor:

```
emi.server      INFO     Started websocket server 0.0.0.0:37321
remi.server      INFO     Started httpserver http://127.0.0.1:8082/
Created new window in existing browser session.
new project
remi.server.ws   INFO     connection established: ('127.0.0.1', 43190)
remi.server.ws   INFO     handshake complete
remi.server.ws   INFO     connection established: ('127.0.0.1', 43288)
remi.server.ws   INFO     handshake complete
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/remi/server.py", line 254, in on_message
    callback(**param_dict)
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 1289, in confirm_dialog
    return self.eventManager.propagate(self.EVENT_ONCONFIRM, ())
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 2265, in confirm_value
    return self.eventManager.propagate(self.EVENT_ONCONFIRMVALUE, params)
  File "/usr/local/lib/python3.5/dist-packages/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
  File "editor.py", line 528, in on_open_dialog_confirm
    widgetTree = self.project.load(filelist[0], self.projectConfiguration)
  File "editor.py", line 115, in load
    return value.construct_ui(self)
  File "/home/afy/remi2/remi-master/editor/buttonpy", line 51, in construct_ui
    top.set_on_click_listener(self.onclick_top)
AttributeError: 'Project' object has no attribute 'onclick_top'

```

**Comment by dddomodossola** [comment]
I will check this soon ;-)

**Comment by MrYsLab** [comment]
Thanks. Another note - if I execute the generated code and add a print statement to the click handler, everything works correctly - the print is executed, so this seems to be limited to loading the file and not anything to do with the code generation. This is the case for both the button and slider.

**Comment by dddomodossola** [comment]
Yeah, found the problem but it is a little bit tricky to solve. I will do it this evening.

**Comment by MrYsLab** [comment]
No problem and there is no hurry. I have everything I need to continue my work. Just to let you know, I was able to open the file I generated with the previous version of the editor. Without changing anything, I just saved in the latest editor and all the signals were converted over. Nice.
![rasberry_redbot_control](https://cloud.githubusercontent.com/assets/5189838/19525701/d9445a6a-95ef-11e6-99a0-48fca0a0c638.png)

**Comment by dddomodossola** [comment]
Hello Alan,

Now the bug is fixed. Consider that the editor lost the compatibility with previously created projects.
In order to reopen an already created project, change your App constructor as follow:

```
    def __init__(self, *args, **kwargs):
        if not 'editing_mode' in kwargs.keys():
            super(untitled, self).__init__(*args, static_file_path='./res/')
```

**Comment by MrYsLab** [comment]
That fixed it thanks.
