### ISSUE TITLE
Editor: Clicking on folder in file chooser results in an exception.

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#142]
I open up the editor and click on a folder icon and the following exception occurs:

```
remi.server      INFO     Started websocket server 0.0.0.0:40919
remi.server      INFO     Started httpserver http://127.0.0.1:8082/
new project
remi.server.ws   INFO     connection established: ('127.0.0.1', 60120)
remi.server.ws   INFO     handshake complete
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/server.py", line 254, in on_message
    callback(**param_dict)
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 484, in onclick
    return self.eventManager.propagate(self.EVENT_ONCLICK, ())
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 2215, in onclick
    return self.eventManager.propagate(self.EVENT_ONCLICK, ())
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
TypeError: on_folder_item_click() missing 1 required positional argument: 'folderitem'


```

**Comment by dddomodossola** [comment]
Will fix this in an hour. Thank you for your valuable testing Alan!

**Comment by dddomodossola** [comment]
Fixed ;-)
