### ISSUE TITLE
Editor: clicking on instances list drop down results in exception

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#143]
I added a top level frame and a button. If I click on the instances list drop down the following exception occurs:

```
remi.server      INFO     Started websocket server 0.0.0.0:43663
remi.server      INFO     Started httpserver http://127.0.0.1:8082/
Created new window in existing browser session.
[8291:8291:1020/115842:ERROR:broker_posix.cc(41)] Invalid node channel message
new project
remi.server.ws   INFO     connection established: ('127.0.0.1', 46364)
remi.server.ws   INFO     handshake complete
('kwargs',)
[]
set_on_blur_listener
set_on_click_listener
set_on_contextmenu_listener
set_on_focus_listener
set_on_mousedown_listener
set_on_mouseleave_listener
set_on_mousemove_listener
set_on_mouseout_listener
set_on_mouseup_listener
set_on_touchcancel_listener
set_on_touchend_listener
set_on_touchenter_listener
set_on_touchleave_listener
set_on_touchmove_listener
set_on_touchstart_listener
selected widget: 140285244477680
set_on_blur_listener
set_on_click_listener
set_on_contextmenu_listener
set_on_focus_listener
set_on_mousedown_listener
set_on_mouseleave_listener
set_on_mousemove_listener
set_on_mouseout_listener
set_on_mouseup_listener
set_on_touchcancel_listener
set_on_touchend_listener
set_on_touchenter_listener
set_on_touchleave_listener
set_on_touchmove_listener
set_on_touchstart_listener
selected widget: 140285244477680
('text', 'kwargs')
['b']
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/server.py", line 254, in on_message
    callback(**param_dict)
  File "/home/afy/PycharmProjects/remi/editor/editor_widgets.py", line 48, in onchange
    return self.eventManager.propagate(self.EVENT_ONCHANGE, (self._selected_item.instance,))
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
TypeError: on_widget_selection() takes 2 positional arguments but 3 were given


```

**Comment by dddomodossola** [comment]
Fixed ;-)
