### ISSUE TITLE
Editor: Adding a labeled checkbox yields exception on save

### ISSUE THREAD

**Issue by MrYsLab** [dddomodossola/remi#145]
I tested this on both Ubuntu and Windows and the behavior is consistent in both. The unlabeled checkbox behaves correctly. 

Procedure to recreate the issue:
Open the editor and add a top level widget and then a labeled checkbox to the top level widget.
Save the project.

Here is the console output:

```
remi.server      INFO     Started websocket server 0.0.0.0:42149
remi.server      INFO     Started httpserver http://127.0.0.1:8082/
new project
remi.server.ws   INFO     connection established: ('127.0.0.1', 51520)
remi.server.ws   INFO     handshake complete
('kwargs',)
[]
set_on_blur_listener
set_on_click_listener
set_on_contextmenu_listener
set_on_focus_listener
set_on_mousedown_listener
set_on_mouseleave_listener
set_on_mousemove_listener
set_on_mouseout_listener
set_on_mouseup_listener
set_on_touchcancel_listener
set_on_touchend_listener
set_on_touchenter_listener
set_on_touchleave_listener
set_on_touchmove_listener
set_on_touchstart_listener
selected widget: 139856362253336
set_on_blur_listener
set_on_click_listener
set_on_contextmenu_listener
set_on_focus_listener
set_on_mousedown_listener
set_on_mouseleave_listener
set_on_mousemove_listener
set_on_mouseout_listener
set_on_mouseup_listener
set_on_touchcancel_listener
set_on_touchend_listener
set_on_touchenter_listener
set_on_touchleave_listener
set_on_touchmove_listener
set_on_touchstart_listener
selected widget: 139856362253336
('label', 'checked', 'user_data', 'kwargs')
['Hi', False, '']
file:/home/afy/untitled.py
top
abc
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/server.py", line 254, in on_message
    callback(**param_dict)
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 1294, in confirm_dialog
    return self.eventManager.propagate(self.EVENT_ONCONFIRM, ())
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
  File "/home/afy/PycharmProjects/remi/editor/editor_widgets.py", line 292, in confirm_value
    return self.eventManager.propagate(self.EVENT_ONCONFIRMVALUE, params)
  File "/usr/local/lib/python3.5/dist-packages/remi-0.1-py3.5.egg/remi/gui.py", line 139, in propagate
    return listener['callback'](self.emitter, *(params+listener['userdata']))
  File "/home/afy/PycharmProjects/remi/editor/editor.py", line 641, in on_saveas_dialog_confirm
    self.project.save(self.projectPathFilename, self.projectConfiguration)
  File "/home/afy/PycharmProjects/remi/editor/editor.py", line 329, in save
    ret = self.repr_widget_for_editor( self.children['root'] )
  File "/home/afy/PycharmProjects/remi/editor/editor.py", line 306, in repr_widget_for_editor
    children_code_nested += self.repr_widget_for_editor(child)
  File "/home/afy/PycharmProjects/remi/editor/editor.py", line 306, in repr_widget_for_editor
    children_code_nested += self.repr_widget_for_editor(child)
  File "/home/afy/PycharmProjects/remi/editor/editor.py", line 255, in repr_widget_for_editor
    widget.path_to_this_widget.append( widget.attributes['editor_varname'] )
KeyError: 'editor_varname'

```

**Comment by dddomodossola** [comment]
Fixed ;-) Thank you
