### ISSUE TITLE
Traceback for no auth header (python3.4)

### ISSUE THREAD

**Issue by bernhardreiter** [dddomodossola/remi#151]
`tail -3 tabbox.py`

``` python
    start(MyApp, debug=True, start_browser=False,
          port=9091, websocket_port=50000,
          username='myuser', password='mypassword')
```

and alling the url with a webbrowser. 

```
python3 tabbox.py 
remi.server      INFO     Started websocket server 127.0.0.1:50000
remi.server      INFO     Started httpserver http://127.0.0.1:9091/
remi.server.http INFO     Authenticating
remi.server.http DEBUG    127.0.0.1 "GET / HTTP/1.1" 401 -
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 45904)
Traceback (most recent call last):
  File "/usr/lib/python3.4/socketserver.py", line 617, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.4/socketserver.py", line 344, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "tabbox.py", line 21, in __init__
    super(MyApp, self).__init__(*args)
  File "/usr/local/lib/python3.4/dist-packages/remi/server.py", line 347, in __init__
    super(App, self).__init__(request, client_address, server)
  File "/usr/lib/python3.4/socketserver.py", line 673, in __init__
    self.handle()
  File "/usr/lib/python3.4/http/server.py", line 398, in handle
    self.handle_one_request()
  File "/usr/lib/python3.4/http/server.py", line 386, in handle_one_request
    method()
  File "/usr/local/lib/python3.4/dist-packages/remi/server.py", line 762, in do_GET
    self.wfile.write('no auth header received')
  File "/usr/lib/python3.4/socket.py", line 394, in write
    return self._sock.send(b)
TypeError: 'str' does not support the buffer interface
```

Expectation a failed authentification should not  lead to a traceback in the backend.

**Comment by dddomodossola** [comment]
@bernhardreiter Thank you for reporting! Now should be fixed.

**Comment by bernhardreiter** [comment]
Ran a quick test with 00ccfb3717f370d30a18cc371d59890a972a123f and it seems to work better now.
@dddomodossola Thanks for publishing remi as Free Software.
