### ISSUE TITLE
widgets_overview_app.py crashes

### ISSUE THREAD

**Issue by hanckmann** [dddomodossola/remi#205]
When trying to run: widgets_overview_app.py
I get the following error/trace:

 $ python widgets_overview_app.py
remi.server      INFO     Started websocket server 0.0.0.0:45725
remi.server      INFO     Started httpserver http://127.0.0.1:8081/
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     DEBUG    127.0.0.1 "HEAD / HTTP/1.1" 200 -
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
remi.request     INFO     built UI (path=/)
remi.request     ERROR    error processing GET request
Traceback (most recent call last):
  File "/projecthome/venv/lib/python3.6/site-packages/remi/server.py", line 788, in do_GET
    self.client.root = self.main(*self.server.userdata)
  File "widgetoverview.py", line 40, in main
    self.table.set_on_table_row_click_listener(self.on_table_row_click)
AttributeError: 'Table' object has no attribute 'set_on_table_row_click_listener'
^[[A^C%

**Comment by socketpair** [comment]
The same.

**Comment by dddomodossola** [comment]
Hello @hanckmann @socketpair , which remi version are you using? If you installed from pypi you have a stable version. The function "set_on_table_row_click_listener" comes from master branch. Please install from master and you will be ok. ;-)
