### ISSUE TITLE
GenericDialog self.hide() no longer works

### ISSUE THREAD

**Issue by jimbob88** [dddomodossola/remi#357]
When working with this example code (a stripped version of the template code):
```python
import remi.gui as gui
from remi import start, App

class MyApp(App):
    def __init__(self, *args):
        super(MyApp, self).__init__(*args)
        x = gui.GenericDialog(title="Hi", message="Hello")
        x.show(self)
        x.hide()

        

if __name__ == "__main__":
    # starts the webserver
    # optional parameters
    # start(MyApp,address='127.0.0.1', port=8081, multiple_instance=False,enable_file_cache=True, update_interval=0.1, start_browser=True)
    start(MyApp, debug=True, address='0.0.0.0', port=0)
```

Errors out saying that the widget cannot hide:
```
Exception happened during processing of request from ('127.0.0.1', 36938)
Traceback (most recent call last):
  File "/usr/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "test5.py", line 10, in __init__
    x.hide()
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.7/site-packages/remi/gui.py", line 2474, in hide
    self._base_app_instance.set_root_widget(self._old_root_widget)
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.7/site-packages/remi/server.py", line 462, in set_root_widget
    self.page.children['body'].append(widget, 'root')
  File "/media/james/Development/Programming/Python/beer_engine/remi/venv/lib/python3.7/site-packages/remi/gui.py", line 1305, in append
    raise ValueError('value should be a Widget (otherwise use add_child(key,other)')
ValueError: value should be a Widget (otherwise use add_child(key,other)
```

I'm not sure why this happens because it says it should be a widget but if you try and open a dialogue from a widget it also errors out because their is no `page` variable.

I cannot tell if I am approaching the dialogue wrong or if it has some fundamental issues that have been broken over time?

Thanks in advance,
Jim

EDIT: For my code I was able to fix it, turned out the issue is if the `construct_ui` happens in the `main` function a `root` class is never initialised and because you cannot call a GenericDialog inside of the `construct_ui` code, to hide I have to force the main code to be ran in the hide function!

**Comment by dddomodossola** [comment]
@jimbob88 , as shown in the issue #356 , a dialog can be shown at startup in App.onpageshow. The App.mian must return the root widget. Having onpageshow you can solve this elegantly.
