### ISSUE TITLE
Impossible to resize/drag objects in the editor

### ISSUE THREAD

**Issue by FlorianPicca** [dddomodossola/remi#358]
When in the GUI editor, trying to drag/resize/select an object produces this kind of error in the logs :
```$ python3 editor/editor.py 
remi.server      INFO     Started httpserver http://0.0.0.0:8082/
remi.request     INFO     built UI (path=/)
new project
127.0.0.1 - - [29/Jan/2020 10:10:33] "GET / HTTP/1.1" 200 -
remi.server.ws   INFO     connection established: ('127.0.0.1', 51052)
remi.server.ws   INFO     handshake complete
-------------used keys:[]
EditorAttributes set widget
selected widget: container0
selected widget class: Container
is widget Container: True
0.21064233779907227
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/home/enoent/.local/lib/python3.6/site-packages/remi/server.py", line 261, in on_message
    callback(**param_dict)
  File "/home/enoent/.local/lib/python3.6/site-packages/remi/gui.py", line 163, in __call__
    return self.callback(self.event_source_instance, *callback_params, **self.kwuserdata)
TypeError: on_drag() got an unexpected keyword argument 'js_prevent_default'
...
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/home/enoent/.local/lib/python3.6/site-packages/remi/server.py", line 261, in on_message
    callback(**param_dict)
  File "/home/enoent/.local/lib/python3.6/site-packages/remi/gui.py", line 163, in __call__
    return self.callback(self.event_source_instance, *callback_params, **self.kwuserdata)
  File "/home/enoent/.local/lib/python3.6/site-packages/remi/gui.py", line 154, in __call__
    callback_params =  self.event_method_bound(*args, **kwargs)
TypeError: stop_drag() got an unexpected keyword argument 'js_prevent_default'
...
remi.server.ws   ERROR    error parsing websocket
Traceback (most recent call last):
  File "/home/enoent/.local/lib/python3.6/site-packages/remi/server.py", line 261, in on_message
    callback(**param_dict)
  File "/home/enoent/Desktop/remi/editor/editor_widgets.py", line 118, in __call__
    self.event_source_instance, *callback_params, **self.kwuserdata)
TypeError: on_widget_selection() got an unexpected keyword argument 'js_stop_propagation'
```
I installed remi using pip like this :
```
python3 -m pip install remi
```

**Comment by dddomodossola** [comment]
Hello @FlorianPicca ,

The problem is that you downloaded the editor from **master** branch that has changes, and you are using the last remi release that is behind the master branch.
Download the editor from here: https://github.com/dddomodossola/remi/tree/2020.1.16

Regards

**Comment by FlorianPicca** [comment]
Hi @dddomodossola ,

My bad. Thanks I got it working now !

Regards

**Comment by dddomodossola** [comment]
You are welcome ;-)
