### ISSUE TITLE
Add my control panel to a web app

### ISSUE THREAD

**Issue by Guohao91** [dddomodossola/remi#363]
Hi, Guys!
Just wonder is that possible to put my the control panel on to webpage? This app is made by Tkinter object, works fine so far to control my drone.So please Davide Rosa or anybody else, can help me this out or any tip like which example I can reference to?

![image](https://user-images.githubusercontent.com/54188732/74963720-34b0c080-53e0-11ea-83db-2967845a69d2.png)
here is a part of my code:
![image](https://user-images.githubusercontent.com/54188732/74964057-b9034380-53e0-11ea-98ae-1e6668553ed8.png)

Thanks in advance! please!

**Comment by Guohao91** [comment]
To put this panel onto web, or make these buttons functional inside a remi.gui's script.

**Comment by dddomodossola** [comment]
Hello @Guohao91 , I can help you. I can't promise to do it in short time because I'm really busy. However it is something simple. 
It is not possible to embed a tkinter gui in a webpage, but it can be rewritten in remi.
Please provide your code in order to rewrite the gui with remi.

**Comment by Guohao91** [comment]
@ yeah yeah, you know what bru. I can understand that is sth simple, but i am not that familiar with javascript and GUI application, because all of the functions I've built up there, so....I am a little embarrassed Lol.
So my script works all fine, no problem, just prompted by dronekit API.
Anyways Thanks Sir!
[blind2.zip](https://github.com/dddomodossola/remi/files/4232521/blind2.zip)
Waiting for your good news!

**Comment by Guohao91** [comment]
@dddomodossola 
 hi, prof. Could you please set those buttons separately into 3 subcontainers? Because I don't have knowledge to design layout, I can learn it by your code at the same time. 
Appreciate it!

**Comment by dddomodossola** [comment]
Hello @Guohao91 ,
Here is the script adapted for remi. I'm unable to test it because I don't have the dependencies installed. But however it's a good start point for you.
[blind2_remi.zip](https://github.com/dddomodossola/remi/files/4235041/blind2_remi.zip)


Regards

**Comment by Guohao91** [comment]
@dear god, you are amazingly fast!
Thanks Davide, give me your email you'd like to send you a gift card.
![image](https://user-images.githubusercontent.com/54188732/75046522-3ab3a980-5493-11ea-965d-2e7e24f5f56a.png)

But just here is a small issue I think, 'str' doesn't have the 'tk' attribute? So would you please take a look at it for a while?

**Comment by Guohao91** [comment]
Connecting to vehicle on: /dev/ttyACM0
INFO:remi.server:Started httpserver http://0.0.0.0:8080/
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'
INFO:remi.request:built UI (path=/)
ERROR:remi.request:error processing GET request
Traceback (most recent call last):
  File "/home/clickmox/.local/lib/python2.7/site-packages/remi/server.py", line 595, in do_GET
    self.set_root_widget(self.main(*self.server.userdata))
  File "blind2_remi.py", line 204, in main
    self.attitudeLabel = Label("No Att", width=120)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2605, in __init__
    Widget.__init__(self, master, 'label', cnf, kw)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2095, in __init__
    BaseWidget._setup(self, master, cnf)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 2073, in _setup
    self.tk = master.tk
AttributeError: 'str' object has no attribute 'tk'

here is the whole log info.

**Comment by dddomodossola** [comment]
@Guohao91 I forgot to remove `from Tkinter import *` , remove it and try again

;-)
my email is dddomodossola@gmail.com

**Comment by Guohao91** [comment]
@dddomodossola 
it is solved!
but....
![image](https://user-images.githubusercontent.com/54188732/75049181-c3344900-5497-11ea-8d6d-be2fe1a0dbc4.png)

the buttons doesn't respond actually....

**Comment by dddomodossola** [comment]
Try with this:
[blind2_remi.zip](https://github.com/dddomodossola/remi/files/4236910/blind2_remi.zip)

unfortunately I can't try it. Let me know if it works

**Comment by Guohao91** [comment]
@dddomodossola 
well, it is all done! You terrific monster!

**Comment by dddomodossola** [comment]
@Guohao91 😉
