### ISSUE TITLE
creating functions in a loop

### ISSUE THREAD

**Issue by simbabali** [dddomodossola/remi#394]
Hello,
i am trying to create a site that can display a random number of buttons. The buttons should all do different tasks. 
So far I created the buttons and the "onclick" events. I am creating the "on_button_pressed" functions in a loop.
When I start up the script everything works as normal. but as soon as I click a button. The Error message below comes up 

```
Traceback (most recent call last):
  File "/home/stan/.local/lib/python3.7/site-packages/remi/server.py", line 261, in on_message
    callback(**param_dict)
  File "/home/stan/.local/lib/python3.7/site-packages/remi/gui.py", line 169, in __call__
    return self.callback(self.event_source_instance, *callback_params, **self.kwuserdata)
TypeError: on_button_pressed() missing 1 required positional argument: 'widget'
```
Here is how the "on_button_pressed" functions are created:

```        functions=[]
            for i in range(3):
                def on_button_pressed(self, widget):
                    print(i)
                functions.append(on_button_pressed)
```

thanks in advance

**Comment by simbabali** [comment]
ok I got I to work after all
```
           for i in range(3):
                def on_button_pressed(widget):
                    print(i)
                functions.append(on_button_pressed)
```
is the way to go

**Comment by dddomodossola** [comment]
;-) well done @simbabali
