### ISSUE TITLE
build fails when using archive since 481ee7ca3df55be127db35560978a36997a2c088

### ISSUE THREAD

**Issue by trabucayre** [dddomodossola/remi#415]
Since PR #404 when using the archive the build fails with:
```
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    setup(
  File "/usr/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 108, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 423, in __init__
    _Distribution.__init__(self, {
  File "/usr/lib/python3.8/distutils/dist.py", line 292, in __init__
    self.finalize_options()
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 695, in finalize_options
    ep(self)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 702, in _finalize_setup_keywords
    ep.load()(self, ep.name, value)
  File "/usr/lib/python3.8/site-packages/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = _get_version(config)
  File "/usr/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 148, in _get_version
    parsed_version = _do_parse(config)
  File "/usr/lib/python3.8/site-packages/setuptools_scm/__init__.py", line 110, in _do_parse
    raise LookupError(
LookupError: setuptools-scm was unable to detect version for '/tmp/remi-2020.10.30'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
```

setuptools_scm search version using git , but in release/tag archives the .git directory has been dropped.

**Comment by dddomodossola** [comment]
@trabucayre Thank you very much for reporting. I will fix this in about 8 hours.

**Comment by dddomodossola** [comment]
@trabucayre Excuse me for the delay. Should be fixed now ;-)

**Comment by trabucayre** [comment]
No worries.
Works for me.

Thanks
